cmake_minimum_required(VERSION 3.20)

if(NOT EXISTS "${WB_JSON_MANIFEST}" OR NOT WB_JSON_DESTINATION)
    message(FATAL_ERROR "The selected JSON include manifest and destination are required")
endif()
file(STRINGS "${WB_JSON_MANIFEST}" include_directories ENCODING UTF-8)
set(selected_headers "")
foreach(directory IN LISTS include_directories)
    if(EXISTS "${directory}/nlohmann/json.hpp")
        set(selected_headers "${directory}/nlohmann")
        break()
    endif()
endforeach()
if(NOT selected_headers)
    message(FATAL_ERROR "The selected nlohmann_json target provides no json.hpp: ${include_directories}")
endif()

file(REAL_PATH "${selected_headers}" source_real)
if(EXISTS "${WB_JSON_DESTINATION}")
    file(REAL_PATH "${WB_JSON_DESTINATION}" destination_real)
else()
    get_filename_component(destination_real "${WB_JSON_DESTINATION}" ABSOLUTE)
endif()
if(NOT source_real STREQUAL destination_real)
    # Replace the generated tree rather than merging files from two releases.
    file(REMOVE_RECURSE "${WB_JSON_DESTINATION}")
    file(MAKE_DIRECTORY "${WB_JSON_DESTINATION}")
    file(COPY "${selected_headers}/" DESTINATION "${WB_JSON_DESTINATION}")
endif()
message(STATUS "Workbench JNI JSON headers: ${selected_headers}")
